development:
  adapter: postgresql
  encoding: unicode
  database: obligator_development
  pool: 5
  username: postgres
  password: 33223322

test:
  adapter: postgresql
  encoding: unicode
  database: obligator_test
  pool: 5
  username: postgres
  password: 33223322
production:
  adapter: postgresql
  prepared_statements: false
  advisory_locks: false
